---
- name: Be Easier on the disk
  hosts: all
  become: true

  tasks:
  - name: Install docker python package
    pip:
      name: docker

  - name: Prune everything
    docker_prune:
      containers: true
      images: true
      networks: false
      volumes: true
      builder_cache: true
