---
- name: Be Easier on the disk
  hosts: all
  become: yes

  tasks:
  - name: Fix journal file usage
    ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      state: present
      regexp: '^#SystemMaxUse='
      line: SystemMaxUse=50M

  - name: Restart journal service
    ansible.builtin.systemd:
      name: systemd-journald.service
      state: restarted

  - name: set docker daemon file 
    ansible.builtin.copy:
      src: files/daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Reload service docker, in all cases
    ansible.builtin.systemd:
      name: docker.service
      state: reloaded
