---
- name: Update and reboot
  hosts: all
  tasks:
  - name: Update all packages with apt
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    become: true
  - name: reboot all systems
    ansible.builtin.reboot:
    become: true
